#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
 
exec-once = $terminal
# exec-once = nm-applet &
exec-once = waybar & hyprpaper 
exec-once = wl-paste --watch cliphist store
exec-once = /usr/lib/xdg-desktop-portal-hyprland
exec-once = /usr/lib/xdg-desktop-portal-gtk

# Start the Idle Daemon for auto-locking
exec-once = swayidle -w timeout 300 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' timeout 600 'hyprlock' before-sleep 'hyprlock'
